# Generated by Django 2.2 on 2019-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalCalendarApp', '0002_auto_20190928_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2019-09-28', verbose_name='date'),
            preserve_default=False,
        ),
    ]
